config/routes.rb
Rails.application.routes.draw do
  devise_for :agents
  root to: "payments#index"

  resource :home
  resources :payments
  resources :statements
end

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :org
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  layout 'agent_layout'
  before_action :authenticate_agent!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dataview_controller.rb
class DataviewController < AppController
  respond_to :html, :js, :json

  def index
    load_collection
  end
  def show
    load_object
  end

  protected
  def load_collection
    params[:q] ||= {}
    @q = object_name.camelize.constantize.order('id desc').ransack(params[:q])
    pages = 20
    @collection = @q.result.page(params[:page]).per(pages)
  end
  def load_object
    @object = object_name.classify.constantize.find_by_id(params[:id])
  end
  def object_name
    controller_name.singularize
  end

end

app/controllers/home_controller.rb
class HomeController < AppController
end

app/controllers/payments_controller.rb
class PaymentsController < DataviewController
end

app/controllers/statements_controller.rb
class StatementsController < AppController
  def index
    redirect_to statement_path(id: DateTime.yesterday.strftime("%Y%m%d"))
  end
  def create
    redirect_to statement_path(id: params[:id])
  end
  def show
    @dt = params[:id]
    @collection = Payment.where(status: 8, order_day: @dt)
    respond_to do |format|
      format.html
      format.csv do
        csv_str = CSV.generate do |csv|
          csv << Payment.column_names
          if @collection
            @collection.each do |pm|
              csv << pm.attributes.values_at(*Payment.column_names)
            end
          end
        end
        send_data csv_str, type: Mime[:csv], disposition: 'inline'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dataview/_edit_form.html.slim
.modal.fade id="#{div_id}" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
        h4.modal-title 
          Edit #{@object.class.name} #{@object.id}
      .modal-body
        = render 'form'
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close
        button.btn.btn-primary onclick="submit_dialog_form(this)" type="button"  Save changes
   

app/views/dataview/_links.html.slim
= link_to '返回', 'javascript:history.back()'

app/views/dataview/create.js.erb
location.reload();

app/views/dataview/edit.html.slim
h1.page-header Editing Object
= link_to 'Show', @object
||
=link_to 'Back', 'javascript:history.back()'
= render 'form'

app/views/dataview/edit.js.erb
var edit_div_id = "edit_<%= @object.class.name.underscore %>_div";
var edit_div = '#' + edit_div_id;
var cnt = "<%=j render(partial: "edit_form", locals: {div_id: "edit_#{@object.class.name.underscore}_div"}) %>";
if ($(edit_div).length == 0){
  $('body').append(cnt);
} else {
  $(edit_div).replaceWith(cnt);
}

$(edit_div)
  .modal('show');

//$('.date-picker').datepicker({ showButtonPanel: true, dateFormat: 'yy-mm-dd' });

app/views/dataview/index.js.erb
$.Dialog({ 
  'title':   'title', 
'content': '<%=j render :partial => 'list' %>', 
  'draggable'   : true,
  'overlay'     : true,
  'closeButton' : true,
  'position': {
    'zone' : 'center'
  },
  'buttons': { 
    'Ok' : { 
      'action' : function(){}
    } 
  } 
});


app/views/dataview/new.html.slim
h1.page-header New object
= link_to '返回列表', send("#{@object.class.name.underscore.split('/').last.pluralize}_path")
= render 'form'

app/views/dataview/new.js.erb
var edit_div_id = "edit_<%= @object.class.name.underscore %>_div";
var edit_div = '#' + edit_div_id;
var cnt = "<%=j render(partial: "edit_form", locals: {div_id: "edit_#{@object.class.name.underscore}_div"}) %>";
if ($(edit_div).length == 0){
  $('body').append(cnt);
} else {
  $(edit_div).replaceWith(cnt);
}

$(edit_div)
  .modal('show');

$('.html-editor').xheditor({tools: 'Blocktag,Bold,Italic,Underline,|,List,Link,Img,|,Source'});	
$('.date-picker').datepicker({ showButtonPanel: true, dateFormat: 'yy-mm-dd' });





app/views/dataview/show.html.slim
= render 'links'
table.table.table-bordered.table-striped.table-hover
  thead
    tr
      th Attribures
      th Value
  tbody
    - @object.attributes.each do |k, v|
      tr
        td= k
        td= v

app/views/dataview/update.js.erb
location.reload();

app/views/home/show.html.slim
h2 Home

app/views/layouts/agent_layout.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    title
      | PooulCloud Gateway
    meta[content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"]
    = csrf_meta_tags

    link[href="/color_admin/assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"]
    link[href="/color_admin/assets/css/animate.min.css" rel="stylesheet"]
    link[href="/color_admin/assets/css/style.min.css" rel="stylesheet"]
    link[href="/color_admin/assets/css/style-responsive.min.css" rel="stylesheet"]
    link#theme[href="/color_admin/assets/css/theme/red.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/jquery-jvectormap/jquery-jvectormap.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/bootstrap-calendar/css/bootstrap_calendar.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/morris/morris.css" rel="stylesheet"]
    link[href="/color_admin/assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" rel="stylesheet"]

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script[src="/color_admin/assets/js/apps.min.js"]


  body
    #page-loader.fade.in
      span.spinner

    #page-container.fade.page-sidebar-fixed.page-header-fixed
      #header.header.navbar.navbar-default.navbar-fixed-top
        .container-fluid
          .navbar-header
            button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand href="/" PooulCloud Gateway
          = render 'shared/main_menu'
    
    .sidebar#sidebar
      ==render 'shared/left_menu'
    .sidebar-bg
                      
    #content.content
      = yield

    footer.footer Copyright © 2015-2016 PooulCloud 保留所有权利

    script[src="/color_admin/assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js"]
    script[src="/color_admin/assets/plugins/pace/pace.min.js"]
    script[src="/color_admin/assets/plugins/gritter/js/jquery.gritter.min.js"]
    javascript:
      //sidemenu();
      //client_show();
      App.init();
      //FormPlugins.init();
      //Dashboard.init();
    
    // 显示flash消息
    - flash.each do |type, message|
      javascript:
        setTimeout( function() {
          $.gritter.add({
            title: '#{type}信息',
            text: '#{message}',
            image: '#{asset_path("messagebox_warning.png")}',
            sticky: false,
            time: '10000',
            class_name: 'my-sticky-class'
            });
            }, 500);

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    == favicon_link_tag '/favicon.png'
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"

    title PooulCloud Gateway
    = stylesheet_link_tag    "application", media: "all"

    link href="/color_admin/assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet"
    link href="/color_admin/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet"
    link href="/color_admin/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"
    link[href="/color_admin/assets/css/style.min.css" rel="stylesheet"]
    link[href="/color_admin/assets/css/style-responsive.min.css" rel="stylesheet"]


  body class='pace-top bg-white'
    div class='fade in' id='page-loader'
      span class='spinner'
    div id='page-container' class='fade'
      .login.login-with-news-feed
        = yield

    script src="/color_admin/assets/plugins/jquery/jquery-1.9.1.min.js"
    script src="/color_admin/assets/plugins/jquery/jquery-migrate-1.1.0.min.js"
    script src="/color_admin/assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js"
    script src="/color_admin/assets/plugins/bootstrap/js/bootstrap.min.js"
    script src="/color_admin/assets/plugins/slimscroll/jquery.slimscroll.min.js"
    script src="/color_admin/assets/plugins/jquery-cookie/jquery.cookie.js"
    script src="/color_admin/assets/js/apps.min.js"
    javascript:
      App.init();

app/views/payments/_filter.html.slim
.filter-wrap.collapsed
  = search_form_for(@q, class: 'search-filter form-inline') do |f|
    //= f.label :order_time, '日期', class: 'form-group m-r-10'
    .form-group.m-r-10
      = f.text_field :order_time_gt, placeholder: '开始时间', class: 'datepicker datepicker-from form-control'
    .form-group.m-r-10
      = f.text_field :order_time_lt, placeholder: '结束时间', class: 'datepicker datepicker-to form-control'

    //= f.label :order_num, '订单号'
    .form-group.m-r-10
      = f.text_field :order_num_cont, placeholder: '订单号', class: 'form-control'

    //= f.label :order_title, '订单标题'
    .form-group.m-r-10
      = f.text_field :order_title_cont, placeholder: '订单标题', class: 'form-control'

    //= f.label :method, '请求类型'
    .form-group.m-r-10
      = f.text_field :method_cont, placeholder: '请求类型', class: 'form-control'

    .form-group.m-r-10
      //= f.label :status, '状态'
      = f.select :status_eq,  Payment.new.status_enum, {}, {class: 'form-control'}

    .form-group.m-r-10
      = f.submit '查找', class: 'btn btn-sm btn-primary m-r-5'

app/views/payments/index.html.slim
p#notice
  = notice
.panel.panel-inverse
  .panel-heading
    h4.panel-title
      | 支付请求列表
  .panel-body.dataTables_wrapper
    = render partial: 'filter'

    //= paginate @collection
    table.table.table-striped.table-bordered.dataTable
      thead
        tr
          th 订单时间
          th 订单号
          th 请求类型
          th 订单标题
          th 金额
          th 支付IP
          th 状态
          th 交易银行
          th 支付渠道
      tbody
        - if @collection
          - @collection.each do |dt|
            tr
              td= dt.order_time.to_datetime.strftime('%Y.%m.%d %H:%M:%S')
              td= link_to dt.order_num, payment_path(dt)
              td= dt.method
              td= dt.order_title
              td= ActiveSupport::NumberHelper.number_to_currency(dt.amount*0.01, unit:'￥')
              td= dt.remote_ip
              td= dt.status_enum.invert[dt.status]
              td= dt.pay_result.bank_type if dt.pay_result
              td= dt.pay_result.channel_name if dt.pay_result
    .row
      .col-sm-5
      .col-sm-7
        .dataTables_paginate.paging_simple_numbers
          = paginate @collection  

app/views/payments/show.html.slim
h2 订单：#{@object.order_num}

table.table.table-bordered style="width: auto;"
  tr
    td 订单时间
    td= @object.order_time
  tr
    td 请求类型
    td= @object.method
  tr
    td 订单标题
    td= @object.order_title
  tr
    td 金额
    td= (@object.amount / 100.00)
  tr
    td 支付IP
    td= @object.remote_ip
  tr
    td 状态
    td= @object.status_enum.invert[@object.status]
  - if @object.pay_result
    tr
      td 交易银行
      td= @object.pay_result.bank_type
    tr
      td 交易渠道
      td= @object.pay_result.channel_name

app/views/shared/_left_menu.html.slim
ul.nav
  li.nav-profile
    div.info
      big 普尔聚合支付网关
      br
      span 商户平台

ul.nav#sidemenu
  li.has-sub.active
    a href="javascript:;" 
      b.caret.pull-right
      i.fa.fa-th
      span 菜单
    ul.sub-menu
      li= link_to '支付列表', payments_path
      li= link_to '每日业务数据总汇表', statements_path
      li
        a href='javascript:;' class='sidebar-minify-btn' data-click='sidebar-minify'
          i class="fa fa-angle-double-left"

app/views/shared/_main_menu.html.slim
ul.nav.navbar-nav.navbar-right
	li= link_to '退出登录', destroy_agent_session_path, :method => :delete

app/views/statements/_filter.html.slim
.filter-wrap.collapsed
  = form_tag(statements_path, class: "form-inline") do
    .form-group.m-r-10
	    = text_field_tag :id, @dt, class: "datepicker datepicker-date form-control", placeholder: '日期'
		.form-group.m-r-10
	    = submit_tag '查找', class: 'btn btn-info'
    .form-group.m-r-10
	    = link_to '导出', statement_path(id: params[:id], format: :csv), class: 'btn btn-info'

app/views/statements/show.html.slim
p#notice
  = notice
.panel.panel-inverse
  .panel-heading
    h4.panel-title
      | 每日业务数据总汇表
  .alert.alert-warning
    | 此表为当日支付成功的业务数据汇总，财务对账以清算数据为准。
  .panel-body.dataTables_wrapper
    = render 'filter'
    table.table.table-striped.table-bordered.dataTable
      thead
        tr
          th 订单时间
          th 订单号
          th 请求类型
          th 订单标题
          th 金额
          th IP
          th 状态
      tbody
        - @collection.each do |dt|
          tr
            td= dt.order_time.to_datetime.strftime('%Y.%m.%d %H:%M:%S')
            td= dt.order_num
            td= dt.method
            td= dt.order_title
            td= ActiveSupport::NumberHelper.number_to_currency(dt.amount*0.01, unit:'￥')
            td= dt.remote_ip
            td= dt.status_enum.invert[dt.status]